'use client';

import { useEffect, useMemo, useState } from 'react';
import { createClient, User } from '@supabase/supabase-js';

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
type Matchup={id:string;title:string;category:string;left_label:string;right_label:string;ends_at:string;matchup_type:'tercih'|'gorus'|'tahmin'};
type Counts=Record<string,{left_votes:number;right_votes:number}>; type ChoiceMap=Record<string,'left'|'right'>;
type Profile={user_id:string;nickname:string;display_name?:string|null;handle_code?:number|null;credits:number;points:number;current_streak:number;best_streak:number;total_predictions:number;correct_predictions:number;notifications_enabled?:boolean;result_alerts?:boolean;trend_alerts?:boolean;daily_reminder?:boolean;vibration_enabled?:boolean;sound_enabled?:boolean};
type Leader={nickname:string;points:number;total_predictions:number;correct_predictions:number};
const interests=['Futbol','Spor','Film/Dizi','Müzik','Teknoloji','Ekonomi','Oyun','Otomobil','Yemek','Seyahat','Moda/Güzellik','Şehir/Yaşam','Dünya Gündemi','Viral/Eğlence'];
const emoji:Record<string,string>={Futbol:'⚽',Spor:'🏀',Şehir:'🏙️',Teknoloji:'📱',Üniversite:'🎓',Yemek:'🍔',Müzik:'🎵',Film:'🎬','Film/Dizi':'🎬',Oyun:'🎮',Ekonomi:'📈',Otomobil:'🚗','Şehir/Yaşam':'🏙️',Seyahat:'✈️','Moda/Güzellik':'✨','Dünya Gündemi':'🌍','Viral/Eğlence':'🔥'};
const typeMeta={tercih:{label:'Tercih',icon:'⚖️'},gorus:{label:'Görüş',icon:'💬'},tahmin:{label:'Tahmin',icon:'🎯'}} as const;
function norm(c:string){if(c==='Şehir')return 'Şehir/Yaşam';if(c==='Film')return 'Film/Dizi';return c;}

export default function Page(){
 const [user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<Profile|null>(null),[matchups,setMatchups]=useState<Matchup[]>([]),[counts,setCounts]=useState<Counts>({}),[choices,setChoices]=useState<ChoiceMap>({}),[leaders,setLeaders]=useState<Leader[]>([]);
 const [referrals,setReferrals]=useState(0),[tab,setTab]=useState<'home'|'rank'|'profile'|'settings'>('home'),[feed,setFeed]=useState<'mine'|'all'>('mine'),[loading,setLoading]=useState(true),[toast,setToast]=useState(''),[feedbackOpen,setFeedbackOpen]=useState(false),[feedback,setFeedback]=useState(''),[rating,setRating]=useState(5),[feedbackDone,setFeedbackDone]=useState(false),[authError,setAuthError]=useState('');
 const [selected,setSelected]=useState<string[]>([]),[interestModal,setInterestModal]=useState(false),[nameModal,setNameModal]=useState(false),[nameInput,setNameInput]=useState('');
 useEffect(()=>{void boot();},[]);
 async function boot(){try{let {data:s}=await supabase.auth.getSession();let u=s.session?.user??null;if(!u){const {data,error}=await supabase.auth.signInAnonymously();if(error)throw error;u=data.user;}if(!u)throw new Error('Anonim kullanıcı oluşturulamadı.');setUser(u);const ref=new URLSearchParams(location.search).get('ref');if(ref&&ref!==u.id)localStorage.setItem('kapis_referrer',ref);await supabase.from('kapis_profiles').upsert({user_id:u.id,nickname:`Kapışçı #${u.id.replaceAll('-','').slice(-5)}`},{onConflict:'user_id',ignoreDuplicates:true});const p=await loadProfile(u.id);await loadInterests(u.id);await Promise.all([loadMatchups(u.id),loadLeaderboard(),loadReferralCount(u.id)]);if(!p?.display_name)setNameModal(true);}catch(e:any){setAuthError(e?.message||'Bağlantı kurulamadı.');}finally{setLoading(false);}}
 async function loadProfile(uid:string){const {data,error}=await supabase.from('kapis_profiles').select('*').eq('user_id',uid).single();if(error)throw error;setProfile(data);const {data:fb}=await supabase.from('kapis_feedback').select('id').eq('user_id',uid).maybeSingle();setFeedbackDone(!!fb);if((data?.total_predictions??0)>=5&&!fb)setFeedbackOpen(true);return data as Profile;}
 async function loadInterests(uid:string){const {data}=await supabase.from('kapis_user_interests').select('interest').eq('user_id',uid);const values=(data??[]).map(x=>x.interest);setSelected(values);if(values.length<3)setInterestModal(true);}
 async function loadReferralCount(uid:string){const {count}=await supabase.from('kapis_referrals').select('id',{count:'exact',head:true}).eq('inviter_id',uid);setReferrals(count??0);}
 async function loadMatchups(uid:string){const [{data:ms,error:me},{data:cs,error:ce},{data:vs,error:ve}]=await Promise.all([supabase.from('kapis_matchups').select('id,title,category,left_label,right_label,ends_at,matchup_type').eq('status','active').gt('ends_at',new Date().toISOString()),supabase.rpc('kapis_matchup_counts'),supabase.from('kapis_votes').select('matchup_id,choice').eq('user_id',uid)]);if(me)throw me;if(ce)throw ce;if(ve)throw ve;setMatchups((ms??[]) as Matchup[]);const nc:Counts={};for(const c of cs??[])nc[c.matchup_id]={left_votes:Number(c.left_votes),right_votes:Number(c.right_votes)};setCounts(nc);const nv:ChoiceMap={};for(const v of vs??[])nv[v.matchup_id]=v.choice;setChoices(nv);}
 async function loadLeaderboard(){const {data}=await supabase.rpc('kapis_leaderboard',{p_limit:20});setLeaders(data??[])}
 async function saveName(){if(!user)return;const n=nameInput.trim();if(n.length<2)return flash('Rumuz en az 2 karakter olmalı.');const {data,error}=await supabase.rpc('kapis_set_display_name',{p_name:n});if(error)return flash('Rumuz kaydedilemedi.');const row=data?.[0];setProfile(p=>p?{...p,display_name:row?.display_name,nickname:row?.nickname,handle_code:row?.handle_code}:p);setNameModal(false);if((selected?.length??0)<3)setInterestModal(true);flash(row?.handle_code?`Rumuzun ${row.nickname} olarak oluşturuldu ✅`:'Rumuzun kaydedildi ✅');}
 async function saveInterests(){if(!user)return;if(selected.length<3)return flash('En az 3 ilgi alanı seç.');await supabase.from('kapis_user_interests').delete().eq('user_id',user.id);const {error}=await supabase.from('kapis_user_interests').insert(selected.map(interest=>({user_id:user.id,interest})));if(error)return flash('İlgi alanları kaydedilemedi.');setInterestModal(false);setFeed('mine');flash('İlgi alanların kaydedildi ✨');}
 async function claimPendingReferral(){const inviter=localStorage.getItem('kapis_referrer');if(!inviter||!user||inviter===user.id)return false;const {data,error}=await supabase.rpc('kapis_claim_referral',{p_inviter_id:inviter});if(!error){localStorage.removeItem('kapis_referrer');return !!data?.length}return false;}
 async function vote(m:Matchup,side:'left'|'right'){if(!user||!profile)return;if(choices[m.id])return flash('Bu Kapış için zaten oy kullandın.');if(profile.credits<=0)return flash('Kredin bitti. Arkadaş davet ederek kredi kazanabilirsin.');const {data,error}=await supabase.rpc('kapis_cast_vote',{p_matchup_id:m.id,p_choice:side});if(error)return flash('Oy kaydedilemedi.');const row=data?.[0],nt=profile.total_predictions+1;setChoices(v=>({...v,[m.id]:side}));setCounts(v=>({...v,[m.id]:{left_votes:Number(row?.left_votes??0),right_votes:Number(row?.right_votes??0)}}));setProfile(p=>p?{...p,credits:Number(row?.credits??p.credits-1),total_predictions:nt}:p);if(profile.vibration_enabled&&'vibrate'in navigator)navigator.vibrate(35);await claimPendingReferral();if(nt>=5&&!feedbackDone)setTimeout(()=>setFeedbackOpen(true),500);void loadLeaderboard();flash('Oyun canlı sisteme kaydedildi ✅');}
 async function shareInvite(){if(!user)return;const url=`${location.origin}/?ref=${user.id}`;const text='KAPIŞ — Tarafını seç. Gündemi belirle. 🔥 İlk kullanıcıya 100 kredi var.';try{if(navigator.share)await navigator.share({title:'KAPIŞ',text,url});else await navigator.clipboard.writeText(url);flash('Davet bağlantısı hazır 🚀')}catch(e:any){if(e?.name!=='AbortError')flash('Paylaşım açılamadı.')}}
 async function submitFeedback(){if(!user||!feedback.trim())return;const {error}=await supabase.from('kapis_feedback').insert({user_id:user.id,rating,comment:feedback.trim()});if(error)return flash('Yorum kaydedilemedi.');setFeedbackDone(true);setFeedbackOpen(false);flash('Teşekkürler! Görüşün kaydedildi.');}
 async function changeSetting(key:keyof Profile,value:boolean){if(!profile)return;let next={notifications_enabled:!!profile.notifications_enabled,result_alerts:profile.result_alerts!==false,trend_alerts:profile.trend_alerts!==false,daily_reminder:!!profile.daily_reminder,vibration_enabled:profile.vibration_enabled!==false,sound_enabled:profile.sound_enabled!==false,[key]:value};if(key==='notifications_enabled'&&value&&'Notification'in window){const perm=await Notification.requestPermission();if(perm!=='granted'){next.notifications_enabled=false;flash('Bildirim izni verilmedi.');}}const {data,error}=await supabase.rpc('kapis_update_settings',{p_notifications_enabled:next.notifications_enabled,p_result_alerts:next.result_alerts,p_trend_alerts:next.trend_alerts,p_daily_reminder:next.daily_reminder,p_vibration_enabled:next.vibration_enabled,p_sound_enabled:next.sound_enabled});if(error)return flash('Ayar kaydedilemedi.');setProfile(data as Profile);if(key==='vibration_enabled'&&value&&'vibrate'in navigator)navigator.vibrate(50);}
 function flash(t:string){setToast(t);setTimeout(()=>setToast(''),2600)}
 const accuracy=profile?.total_predictions?Math.round(profile.correct_predictions/profile.total_predictions*100):0,totalVotes=useMemo(()=>Object.values(counts).reduce((a,b)=>a+b.left_votes+b.right_votes,0),[counts]);
 const visible=useMemo(()=>{const list=feed==='all'?[...matchups]:matchups.filter(m=>selected.includes(norm(m.category))||selected.includes(m.category));return list.sort((a,b)=>{const av=(counts[a.id]?.left_votes??0)+(counts[a.id]?.right_votes??0),bv=(counts[b.id]?.left_votes??0)+(counts[b.id]?.right_votes??0);return feed==='all'?bv-av:new Date(a.ends_at).getTime()-new Date(b.ends_at).getTime();});},[feed,matchups,selected,counts]);
 if(loading)return <main className="center"><Logo/><p>Canlı sisteme bağlanıyor…</p></main>;if(authError)return <main className="center"><Logo/><h2>Bağlantı ayarı gerekiyor</h2><p className="muted">{authError}</p></main>;
 return <main><header><div className="brandWrap"><Logo/><div className="tag">Tarafını seç. Gündemi belirle.</div></div><div className="credit">🎁 {profile?.credits??100} kredi</div></header><section className="stats"><div>🔥 <b>{profile?.current_streak??0}</b><span>seri</span></div><div>🏆 <b>{profile?.points??0}</b><span>puan</span></div><div>🎯 <b>%{accuracy}</b><span>isabet</span></div></section>
 {tab==='home'&&<><div className="hero"><span>KAPIŞ — TARAFINI SEÇ</span><h1>Gündem oylamaya dönüşüyor.</h1><p>Spor, dizi, müzik, teknoloji, ekonomi, şehir ve viral konularda tarafını seç.</p></div><div className="invite"><span>🎁 ARKADAŞ DAVETİ</span><h3>Gönder, +10 kredi kazan</h3><p>Arkadaşın ilk Kapışını yaptığında kredi otomatik gelir.</p><button onClick={shareInvite}>📤 Arkadaşıma gönder</button><small>{referrals} arkadaş katıldı • +{referrals*10} kredi kazandın</small></div><div className="live"><i/> CANLI BETA • {totalVotes.toLocaleString('tr-TR')} oy toplandı</div><div className="feedTabs"><button className={feed==='mine'?'active':''} onClick={()=>setFeed('mine')}>✨ İlgim</button><button className={feed==='all'?'active':''} onClick={()=>setFeed('all')}>🇹🇷 Genel</button><button className="editInterests" onClick={()=>setInterestModal(true)}>⚙️</button></div><h2>{feed==='mine'?'✨ Sana göre Kapışlar':'🔥 Türkiye ne konuşuyor?'}</h2><div className="cards">{visible.map(m=>{const c=counts[m.id]??{left_votes:0,right_votes:0},t=c.left_votes+c.right_votes,lp=t?Math.round(c.left_votes/t*100):50,ch=choices[m.id],h=Math.max(0,Math.ceil((new Date(m.ends_at).getTime()-Date.now())/3600000)),tm=typeMeta[m.matchup_type]??typeMeta.tercih;return <article key={m.id}><div className="meta"><span>{emoji[m.category]??'🔥'} {m.category}</span><small>⏱ {h} saat</small></div><div className={`typeBadge ${m.matchup_type}`}>{tm.icon} {tm.label}</div><h3 className="question">{m.title}</h3><div className="duel"><button className={ch==='left'?'picked':''} onClick={()=>vote(m,'left')}><strong>{m.left_label}</strong><em>%{lp}</em><small>{c.left_votes} oy</small></button><b>VS</b><button className={ch==='right'?'picked':''} onClick={()=>vote(m,'right')}><strong>{m.right_label}</strong><em>%{100-lp}</em><small>{c.right_votes} oy</small></button></div><div className="bar"><i style={{width:`${lp}%`}}/></div><div className="status">{ch?`Seçimin: ${ch==='left'?m.left_label:m.right_label}`:m.matchup_type==='tahmin'?'Tahminini yap':'Tarafını seç'}</div><div className="commentGate">💬 {(profile?.total_predictions??0)>=5?'Yorum hakkın açık':'Yorumlar 5 Kapış sonrası açılır'}</div></article>})}</div></>}
 {tab==='rank'&&<section><h2>🏆 Canlı Sıralama</h2><div className="panel">{leaders.map((x,i)=><div className={x.nickname===profile?.nickname?'row me':'row'} key={`${x.nickname}-${i}`}><span>#{i+1} {x.nickname}</span><b>{x.total_predictions} Kapış</b></div>)}</div></section>}
 {tab==='profile'&&<section><h2>👤 Profil</h2><div className="panel profile"><div className="avatar">K</div><h3>{profile?.nickname}</h3><p>KAPIŞ ilk kullanıcı</p><div className="grid"><div><b>{profile?.total_predictions??0}</b><span>Katılım</span></div><div><b>{profile?.correct_predictions??0}</b><span>Doğru tahmin</span></div><div><b>%{accuracy}</b><span>Başarı</span></div><div><b>{profile?.current_streak??0}</b><span>Seri</span></div></div><div className="expertise"><b>🏅 Kategori uzmanlığı</b><span>Tahminler sonuçlandıkça rozetlerin burada oluşacak.</span></div><button className="shareProfile" onClick={shareInvite}>📤 Arkadaşına gönder • +10 kredi</button></div></section>}
 {tab==='settings'&&<section><h2>⚙️ Ayarlar</h2><div className="panel settings"><Setting title="🔔 Bildirimler" desc="Kapış sonuçları ve önemli gelişmeler" on={!!profile?.notifications_enabled} toggle={v=>changeSetting('notifications_enabled',v)}/><Setting title="🎯 Sonuç uyarıları" desc="Tahminlerin sonuçlandığında haber ver" on={profile?.result_alerts!==false} toggle={v=>changeSetting('result_alerts',v)}/><Setting title="🔥 Trend uyarıları" desc="İlgi alanlarında güçlü bir gündem yükseldiğinde" on={profile?.trend_alerts!==false} toggle={v=>changeSetting('trend_alerts',v)}/><Setting title="📅 Günlük hatırlatma" desc="Günün Kapışlarını kaçırma" on={!!profile?.daily_reminder} toggle={v=>changeSetting('daily_reminder',v)}/><Setting title="📳 Titreşim" desc="Oy verdiğinde kısa geri bildirim" on={profile?.vibration_enabled!==false} toggle={v=>changeSetting('vibration_enabled',v)}/><Setting title="🔊 Ses" desc="Uygulama içi ses efektleri" on={profile?.sound_enabled!==false} toggle={v=>changeSetting('sound_enabled',v)}/><button className="settingsAction" onClick={()=>{setNameInput(profile?.display_name||'');setNameModal(true)}}>✏️ Rumuzu değiştir</button><button className="settingsAction" onClick={()=>setInterestModal(true)}>✨ İlgi alanlarını düzenle</button></div></section>}
 <nav><button className={tab==='home'?'on':''} onClick={()=>setTab('home')}>⚡<span>Ana Sayfa</span></button><button className={tab==='rank'?'on':''} onClick={()=>setTab('rank')}>🏆<span>Sıralama</span></button><button className={tab==='profile'?'on':''} onClick={()=>setTab('profile')}>👤<span>Profil</span></button><button className={tab==='settings'?'on':''} onClick={()=>setTab('settings')}>⚙️<span>Ayarlar</span></button></nav>
 {toast&&<div className="toast">{toast}</div>}
 {nameModal&&<div className="modal"><div className="sheet"><div className="pill"/><Logo/><h2>Sana nasıl hitap edelim?</h2><p>İstediğin rumuzu yaz. Aynı rumuzu başkası kullanıyorsa engellemeyiz; otomatik <b>#1234</b> gibi bir etiket ekleriz.</p><input className="nameInput" autoFocus maxLength={24} value={nameInput} onChange={e=>setNameInput(e.target.value)} placeholder="Örn. Erdem"/><button className="primary" onClick={saveName}>Devam et</button>{profile?.display_name&&<button className="ghost" onClick={()=>setNameModal(false)}>Vazgeç</button>}</div></div>}
 {interestModal&&!nameModal&&<div className="modal interestsModal"><div className="sheet"><div className="pill"/><Logo/><h2>Neler ilgini çekiyor?</h2><p>En az 3 seçim yap. Akışını buna göre düzenleyeceğiz.</p><span className="selectionCount">{selected.length}/3 minimum</span><div className="interestGrid">{interests.map(x=><button key={x} className={selected.includes(x)?'chosen':''} onClick={()=>setSelected(s=>s.includes(x)?s.filter(v=>v!==x):[...s,x])}>{emoji[x]??'🔥'} {x}</button>)}</div><button className="primary" onClick={saveInterests}>İlgimi oluştur</button>{selected.length>=3&&<button className="ghost" onClick={()=>setInterestModal(false)}>Vazgeç</button>}</div></div>}
 {feedbackOpen&&!nameModal&&!interestModal&&<div className="modal"><div className="sheet"><div className="pill"/><h2>5 Kapış yaptın! 👏</h2><p>20 saniyelik görüşün bizim için çok değerli.</p><div className="stars">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setRating(n)} className={rating>=n?'active':''}>★</button>)}</div><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="En çok neyi sevdin / neyi değiştirelim?"/><button className="primary" onClick={submitFeedback}>Yorumu gönder</button><button className="ghost" onClick={()=>setFeedbackOpen(false)}>Sonra</button></div></div>}</main>;
}
function Logo(){return <div className="kapisLogo"><span className="logoMark"><i>K</i><b>VS</b></span><strong>KAPIŞ</strong></div>}
function Setting({title,desc,on,toggle}:{title:string;desc:string;on:boolean;toggle:(v:boolean)=>void}){return <div className="settingRow"><div><b>{title}</b><span>{desc}</span></div><button className={on?'switch on':'switch'} onClick={()=>toggle(!on)}><i/></button></div>}
