'use client';

import { useEffect, useMemo, useState } from 'react';
import { createClient, User } from '@supabase/supabase-js';

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
type Matchup={id:string;title:string;category:string;left_label:string;right_label:string;ends_at:string};
type Counts=Record<string,{left_votes:number;right_votes:number}>; type ChoiceMap=Record<string,'left'|'right'>;
type Profile={user_id:string;nickname:string;credits:number;points:number;current_streak:number;best_streak:number;total_predictions:number;correct_predictions:number};
type Leader={nickname:string;points:number;total_predictions:number;correct_predictions:number};
const interests=['Futbol','Spor','Film/Dizi','Müzik','Teknoloji','Ekonomi','Oyun','Yemek','Seyahat','Moda/Güzellik','Otomobil','Şehir/Yaşam','Dünya Gündemi','Viral/Eğlence'];
const emoji:Record<string,string>={Futbol:'⚽',Spor:'🏀',Şehir:'🏙️',Teknoloji:'📱',Üniversite:'🎓',Yemek:'🍔',Müzik:'🎵',Film:'🎬','Film/Dizi':'🎬',Oyun:'🎮',Ekonomi:'📈',Otomobil:'🚗','Şehir/Yaşam':'🏙️'};
function norm(c:string){if(c==='Şehir')return 'Şehir/Yaşam'; if(c==='Film')return 'Film/Dizi'; return c;}

export default function Page(){
 const [user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<Profile|null>(null),[matchups,setMatchups]=useState<Matchup[]>([]),[counts,setCounts]=useState<Counts>({}),[choices,setChoices]=useState<ChoiceMap>({}),[leaders,setLeaders]=useState<Leader[]>([]);
 const [referrals,setReferrals]=useState(0),[tab,setTab]=useState<'home'|'rank'|'profile'>('home'),[feed,setFeed]=useState<'mine'|'all'>('mine'),[loading,setLoading]=useState(true),[toast,setToast]=useState(''),[feedbackOpen,setFeedbackOpen]=useState(false),[feedback,setFeedback]=useState(''),[rating,setRating]=useState(5),[feedbackDone,setFeedbackDone]=useState(false),[authError,setAuthError]=useState('');
 const [selected,setSelected]=useState<string[]>([]),[onboarding,setOnboarding]=useState(false);
 useEffect(()=>{void boot();},[]);
 async function boot(){try{let {data:s}=await supabase.auth.getSession();let u=s.session?.user??null;if(!u){const {data,error}=await supabase.auth.signInAnonymously();if(error)throw error;u=data.user;}if(!u)throw new Error('Anonim kullanıcı oluşturulamadı.');setUser(u);const saved=localStorage.getItem('kapis_interests');if(saved)setSelected(JSON.parse(saved));else setOnboarding(true);const ref=new URLSearchParams(location.search).get('ref');if(ref&&ref!==u.id)localStorage.setItem('kapis_referrer',ref);await supabase.from('kapis_profiles').upsert({user_id:u.id,nickname:`Kapışçı #${u.id.replaceAll('-','').slice(-5)}`},{onConflict:'user_id',ignoreDuplicates:true});await Promise.all([loadProfile(u.id),loadMatchups(u.id),loadLeaderboard(),loadReferralCount(u.id)]);}catch(e:any){setAuthError(e?.message||'Bağlantı kurulamadı.');}finally{setLoading(false);}}
 async function loadProfile(uid:string){const {data,error}=await supabase.from('kapis_profiles').select('*').eq('user_id',uid).single();if(error)throw error;setProfile(data);const {data:fb}=await supabase.from('kapis_feedback').select('id').eq('user_id',uid).maybeSingle();setFeedbackDone(!!fb);if((data?.total_predictions??0)>=5&&!fb)setFeedbackOpen(true);}
 async function loadReferralCount(uid:string){const {count}=await supabase.from('kapis_referrals').select('id',{count:'exact',head:true}).eq('inviter_id',uid);setReferrals(count??0);}
 async function loadMatchups(uid:string){const [{data:ms,error:me},{data:cs,error:ce},{data:vs,error:ve}]=await Promise.all([supabase.from('kapis_matchups').select('id,title,category,left_label,right_label,ends_at').eq('status','active').gt('ends_at',new Date().toISOString()).order('ends_at'),supabase.rpc('kapis_matchup_counts'),supabase.from('kapis_votes').select('matchup_id,choice').eq('user_id',uid)]);if(me)throw me;if(ce)throw ce;if(ve)throw ve;setMatchups(ms??[]);const nc:Counts={};for(const c of cs??[])nc[c.matchup_id]={left_votes:Number(c.left_votes),right_votes:Number(c.right_votes)};setCounts(nc);const nv:ChoiceMap={};for(const v of vs??[])nv[v.matchup_id]=v.choice;setChoices(nv);}
 async function loadLeaderboard(){const {data}=await supabase.rpc('kapis_leaderboard',{p_limit:20});setLeaders(data??[])}
 async function claimPendingReferral(){const inviter=localStorage.getItem('kapis_referrer');if(!inviter||!user||inviter===user.id)return false;const {data,error}=await supabase.rpc('kapis_claim_referral',{p_inviter_id:inviter});if(!error){localStorage.removeItem('kapis_referrer');return !!data?.length}return false;}
 async function vote(m:Matchup,side:'left'|'right'){if(!user||!profile)return;if(choices[m.id])return flash('Bu Kapış için zaten tahmin yaptın.');if(profile.credits<=0)return flash('Kredin bitti. Arkadaş davet ederek kredi kazanabilirsin.');const {data,error}=await supabase.rpc('kapis_cast_vote',{p_matchup_id:m.id,p_choice:side});if(error)return flash(error.message.includes('duplicate')?'Bu Kapış için zaten oy kullandın.':'Oy kaydedilemedi.');const row=data?.[0];setChoices(v=>({...v,[m.id]:side}));setCounts(v=>({...v,[m.id]:{left_votes:Number(row?.left_votes??0),right_votes:Number(row?.right_votes??0)}}));const nt=profile.total_predictions+1;setProfile(p=>p?{...p,credits:Number(row?.credits??p.credits-1),total_predictions:nt}:p);const claimed=await claimPendingReferral();if(nt>=5&&!feedbackDone)setTimeout(()=>setFeedbackOpen(true),500);void loadLeaderboard();flash(claimed?'Tahmin kaydedildi ✅ Davetin tamamlandı; arkadaşın +10 kredi kazandı.':'Tahminin canlı sisteme kaydedildi ✅');}
 async function shareInvite(){if(!user)return;const url=`${location.origin}/?ref=${user.id}`;const text='KAPIŞ — Tarafını seç. Türkiye ne düşünüyor gör 🔥 İlk kullanıcıya 100 kredi var.';try{if(navigator.share){await navigator.share({title:'KAPIŞ',text,url});flash('Davet bağlantısı hazır 🚀')}else{await navigator.clipboard.writeText(url);flash('Davet linki kopyalandı ✅')}}catch(e:any){if(e?.name!=='AbortError')flash('Paylaşım açılamadı.')}}
 async function submitFeedback(){if(!user||!feedback.trim())return;const {error}=await supabase.from('kapis_feedback').insert({user_id:user.id,rating,comment:feedback.trim()});if(error)return flash('Yorum kaydedilemedi.');setFeedbackDone(true);setFeedbackOpen(false);flash('Teşekkürler! Görüşün canlı olarak kaydedildi.');}
 function saveInterests(){if(!selected.length)return flash('En az 1 ilgi alanı seç.');localStorage.setItem('kapis_interests',JSON.stringify(selected));setOnboarding(false);setFeed('mine');}
 function flash(t:string){setToast(t);setTimeout(()=>setToast(''),2600)}
 const accuracy=profile?.total_predictions?Math.round(profile.correct_predictions/profile.total_predictions*100):0,totalVotes=useMemo(()=>Object.values(counts).reduce((a,b)=>a+b.left_votes+b.right_votes,0),[counts]);
 const visible=feed==='all'?matchups:matchups.filter(m=>selected.includes(norm(m.category))||selected.includes(m.category));
 if(loading)return <main className="center"><Logo/><p>Canlı sisteme bağlanıyor…</p></main>;if(authError)return <main className="center"><Logo/><h2>Bağlantı ayarı gerekiyor</h2><p className="muted">{authError}</p></main>;
 return <main>
  <header><div className="brandWrap"><Logo/><div className="tag">Tarafını seç.</div></div><div className="credit">🎁 {profile?.credits??100} kredi</div></header>
  <section className="stats"><div>🔥 <b>{profile?.current_streak??0}</b><span>seri</span></div><div>🏆 <b>{profile?.points??0}</b><span>puan</span></div><div>🎯 <b>%{accuracy}</b><span>isabet</span></div></section>
  {tab==='home'&&<><div className="hero"><span>TÜRKİYE NE DÜŞÜNÜYOR?</span><h1>Tarafını seç. Kapış başlasın.</h1><p>İlk kullanıcılar 100 krediyle başlıyor. İlk 5 Kapışını yap, fikrini söyle.</p></div><div className="invite"><div><span>🎁 ARKADAŞ DAVETİ</span><h3>Gönder, +10 kredi kazan</h3><p>Arkadaşın ilk Kapışını yaptığında kredi otomatik gelir.</p></div><button onClick={shareInvite}>📤 Arkadaşıma gönder</button><small>{referrals} arkadaş katıldı • +{referrals*10} kredi kazandın</small></div><div className="live"><i/> CANLI BETA • {totalVotes.toLocaleString('tr-TR')} oy toplandı</div><div className="feedTabs"><button className={feed==='mine'?'active':''} onClick={()=>setFeed('mine')}>✨ İlgim</button><button className={feed==='all'?'active':''} onClick={()=>setFeed('all')}>🌍 Genel</button><button className="editInterests" onClick={()=>setOnboarding(true)}>⚙️</button></div><h2>{feed==='mine'?'✨ Sana göre Kapışlar':'🔥 Şu an Kapışanlar'}</h2>{!visible.length&&<div className="panel empty"><b>İlgine uygun aktif Kapış yok.</b><p>Genel akışa geçebilir veya ilgi alanlarını düzenleyebilirsin.</p></div>}<div className="cards">{visible.map(m=>{const c=counts[m.id]??{left_votes:0,right_votes:0},t=c.left_votes+c.right_votes,lp=t?Math.round(c.left_votes/t*100):50,ch=choices[m.id],h=Math.max(0,Math.ceil((new Date(m.ends_at).getTime()-Date.now())/3600000));return <article key={m.id}><div className="meta"><span>{emoji[m.category]??'🔥'} {m.category}</span><small>⏱ {h} saat</small></div><div className="duel"><button className={ch==='left'?'picked':''} onClick={()=>vote(m,'left')}><strong>{m.left_label}</strong><em>%{lp}</em><small>{c.left_votes} güç</small></button><b>VS</b><button className={ch==='right'?'picked':''} onClick={()=>vote(m,'right')}><strong>{m.right_label}</strong><em>%{100-lp}</em><small>{c.right_votes} güç</small></button></div><div className="bar"><i style={{width:`${lp}%`}}/></div><div className="status">{ch?`Tahminin: ${ch==='left'?m.left_label:m.right_label}`:'Tarafını seç ve sonucu tahmin et'}</div></article>})}</div></>}
  {tab==='rank'&&<section><h2>🏆 Canlı Sıralama</h2><div className="panel">{leaders.map((x,i)=><div className={x.nickname===profile?.nickname?'row me':'row'} key={`${x.nickname}-${i}`}><span>#{i+1} {x.nickname}</span><b>{x.total_predictions} Kapış</b></div>)}</div></section>}
  {tab==='profile'&&<section><h2>👤 Profil</h2><div className="panel profile"><div className="avatar"><span>K</span></div><h3>{profile?.nickname}</h3><p>KAPIŞ ilk kullanıcı • 100 kredi kampanyası</p><div className="grid"><div><b>{profile?.total_predictions??0}</b><span>Tahmin</span></div><div><b>{profile?.correct_predictions??0}</b><span>Doğru</span></div><div><b>{referrals}</b><span>Davet</span></div><div><b>+{referrals*10}</b><span>Davet kredisi</span></div></div><button className="shareProfile" onClick={shareInvite}>📤 Arkadaşına gönder • +10 kredi</button>{feedbackDone&&<div className="thanks">✅ İlk kullanıcı geri bildirimi tamamlandı.</div>}</div></section>}
  <nav><button className={tab==='home'?'on':''} onClick={()=>setTab('home')}>⚡<span>Ana Sayfa</span></button><button className={tab==='rank'?'on':''} onClick={()=>setTab('rank')}>🏆<span>Sıralama</span></button><button className={tab==='profile'?'on':''} onClick={()=>setTab('profile')}>👤<span>Profil</span></button></nav>
  {toast&&<div className="toast">{toast}</div>}
  {onboarding&&<div className="modal interestsModal"><div className="sheet"><div className="pill"/><Logo/><h2>Neler ilgini çekiyor?</h2><p>Akışını buna göre düzenleyeceğiz. Futbol istemiyorsan futbol görmek zorunda değilsin.</p><div className="interestGrid">{interests.map(x=><button key={x} className={selected.includes(x)?'chosen':''} onClick={()=>setSelected(s=>s.includes(x)?s.filter(v=>v!==x):[...s,x])}>{emoji[x]??'🔥'} {x}</button>)}</div><button className="primary" onClick={saveInterests}>İlgimi oluştur</button>{localStorage.getItem('kapis_interests')&&<button className="ghost" onClick={()=>setOnboarding(false)}>Vazgeç</button>}</div></div>}
  {feedbackOpen&&<div className="modal"><div className="sheet"><div className="pill"/><h2>5 Kapış yaptın! 👏</h2><p>20 saniyelik görüşün bizim için çok değerli.</p><div className="stars">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setRating(n)} className={rating>=n?'active':''}>★</button>)}</div><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="En çok neyi sevdin / neyi değiştirelim?"/><button className="primary" onClick={submitFeedback}>Yorumu gönder</button><button className="ghost" onClick={()=>setFeedbackOpen(false)}>Sonra</button></div></div>}
 </main>;
}
function Logo(){return <div className="kapisLogo"><span className="logoMark"><i>K</i><b>VS</b></span><strong>KAPIŞ</strong></div>}
